// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8xLKBvf-O6C2OLftNWfcuhGDnHNl35cM',
    appId: '1:1057751147931:web:79052ac0c7ac1d05abed3e',
    messagingSenderId: '1057751147931',
    projectId: 'midcare-73d85',
    authDomain: 'midcare-73d85.firebaseapp.com',
    storageBucket: 'midcare-73d85.firebasestorage.app',
    measurementId: 'G-DSKLQW9HHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEEEIR_3pZxnXboTXyKdpNWc6aGzGIE8k',
    appId: '1:1057751147931:android:e9d47a3dc92d5264abed3e',
    messagingSenderId: '1057751147931',
    projectId: 'midcare-73d85',
    storageBucket: 'midcare-73d85.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD__VqLY0DBHYCzr6MKL5AUASNu0mPMqsc',
    appId: '1:1057751147931:ios:ce1a292753baf7d6abed3e',
    messagingSenderId: '1057751147931',
    projectId: 'midcare-73d85',
    storageBucket: 'midcare-73d85.firebasestorage.app',
    iosClientId: '1057751147931-mjubhiv3skm5f8h3scu2uf7d8ah8kv6v.apps.googleusercontent.com',
    iosBundleId: 'com.comsats.medremind.medicineReminderApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD__VqLY0DBHYCzr6MKL5AUASNu0mPMqsc',
    appId: '1:1057751147931:ios:ce1a292753baf7d6abed3e',
    messagingSenderId: '1057751147931',
    projectId: 'midcare-73d85',
    storageBucket: 'midcare-73d85.firebasestorage.app',
    iosClientId: '1057751147931-mjubhiv3skm5f8h3scu2uf7d8ah8kv6v.apps.googleusercontent.com',
    iosBundleId: 'com.comsats.medremind.medicineReminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8xLKBvf-O6C2OLftNWfcuhGDnHNl35cM',
    appId: '1:1057751147931:web:2ecce1666aeb7d7eabed3e',
    messagingSenderId: '1057751147931',
    projectId: 'midcare-73d85',
    authDomain: 'midcare-73d85.firebaseapp.com',
    storageBucket: 'midcare-73d85.firebasestorage.app',
    measurementId: 'G-SKVGKGKMZQ',
  );
}
